version: '3.7'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80


# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
